function [...
    PilotLocations, ...
    PilotModulatedX, ...
    PilotModulatedY, ...
    PilotModulatedXIFFT, ...
    PilotModulatedYIFFT, ...
    X, ...
    Y, ...
    TxPilots, ...
    RxPilots ...
    ] = GetSimpleChannelData( ...
                Channels, ...
                TransmissionsPerChannel, ...
                SNR, ...
                Modulation, ...
                BitLength, ...
                PilotSpacing, ...
                PilotValue, ...
                Duplications)
    X = []; Y = [];
    PilotModulatedX = []; PilotModulatedY = [];
    PilotModulatedXIFFT = []; PilotModulatedYIFFT = [];
    RxPilots = []; TxPilots = [];
    for j = 1:Channels
        [rayc, awgn] = GenerateChannel(10, SNR, 1, 1, false);
        for i = 1:TransmissionsPerChannel
            [rx_pilots, tx_pilots, PilotLocations, ...
                pilot_modulated_x, y_modulated_pilot, ...
                x, y, ...
                IFFT_pilot_modulated_x, y_modulated_pilot_IFFT] ... 
            = ExecuteChannel(...
                    Modulation, ...
                    BitLength, ...
                    PilotSpacing, ...
                    PilotValue, ...
                    Duplications, ...
                    rayc, ...
                    awgn, ...
                    true);
            AMENDMENT_PilotModulatedX       = cat(1, real(pilot_modulated_x), imag(pilot_modulated_x));
            AMENDMENT_PilotModulatedY       = cat(1, real(y_modulated_pilot), imag(y_modulated_pilot));
            AMENDMENT_PilotModulatedXIFFT   = cat(1, real(IFFT_pilot_modulated_x), imag(IFFT_pilot_modulated_x));
            AMENDMENT_PilotModulatedYIFFT   = cat(1, real(y_modulated_pilot_IFFT), imag(y_modulated_pilot_IFFT));
            AMENDMENT_X                     = cat(1, real(x), imag(x));
            AMENDMENT_Y                     = cat(1, real(y), imag(y));
            AMENDMENT_RxPilots              = cat(1, real(rx_pilots), imag(rx_pilots));
            AMENDMENT_TxPilots              = cat(1, real(tx_pilots), imag(tx_pilots));

            PilotModulatedX     = cat(2, PilotModulatedX,  AMENDMENT_PilotModulatedX.');
            PilotModulatedY     = cat(2, PilotModulatedY,  AMENDMENT_PilotModulatedY.');
            PilotModulatedXIFFT = cat(2, PilotModulatedXIFFT,  AMENDMENT_PilotModulatedXIFFT.');
            PilotModulatedYIFFT = cat(2, PilotModulatedYIFFT,  AMENDMENT_PilotModulatedYIFFT.');
            X                   = cat(2, X,  AMENDMENT_X.');
            Y                   = cat(2, Y,  AMENDMENT_Y.');
            TxPilots            = cat(2, RxPilots,  AMENDMENT_RxPilots.');
            RxPilots            = cat(2, TxPilots,  AMENDMENT_TxPilots.');
        end
    end
end