clear variables;
close all;

%% Channel simulation configuration
includeAWGN             = true;
includeChannel          = true;
Channels                = 1000;
TransmissionsPerChannel = 1;
M                       = 32;
Scaling                 = 1.0;
SNR                     = 50;
MDS                     = 100;
Modulation              = 4;
BitLength               = 4;
PilotSpacing            = 4;
PilotValue              = -0.123 + 0.123*1i;

SymbolDuplications      = 4;
ModulationDuplications  = 1;
PilotDuplications       = 4;

%% Creating training Data
[ LSTM_INPUT, ... 
  FFT_X, FFT_Y, ...
  IFFT_X, IFFT_Y, ...
  CHANNEL_H, ...
  SYMBOL_X, SYMBOL_Y, ...
  PILOTS_X, PILOTS_Y ...
  ] = GenerateLSTMData( ...
                Channels, ...
                TransmissionsPerChannel, ...
                M, ...
                Scaling, ...
                SNR, ...
                MDS, ...
                Modulation, ...
                BitLength, ...
                PilotSpacing, ...
                PilotValue, ...
                SymbolDuplications, ...
                ModulationDuplications, ...
                PilotDuplications, ...
                includeAWGN, ...
                includeChannel);
save("LSTMTRAININGDATA.mat", "LSTM_INPUT", "CHANNEL_H");
save("LSTMEQUALISATION.mat", "IFFT_X", "IFFT_Y");
save("LSTMTRAININGSYMBOLERRORS.mat", "SYMBOL_X", "SYMBOL_Y");

