%% Load Validation data
load("LSTMVALIDATIONDATA.mat", "LSTM_VALID_INPUT", "CHANNEL_VALID_H")
ValidationData = {LSTM_VALID_INPUT, CHANNEL_VALID_H};

%% LSTM Configuration
InputUnits = 128;
HiddenUnits = 1000;
MiddleUnits = 1000;
OutputUnits = 64;
MaxEpochs = 50;
MiniBatchSize = 128;
InitialLearningRate = 0.001;
LearningRateDropPeriod = 25;
LearningRateDropFactor = 0.9;
Regularisation = 0.001;
%% Creating LSTM
lstm = LSTM;
lstm = lstm.GenerateLSTM(...
                InputUnits, ...
                HiddenUnits, ...
                MiddleUnits, ...
                OutputUnits, ...
                MaxEpochs, ...
                MiniBatchSize, ...
                InitialLearningRate, ...
                LearningRateDropPeriod, ...
                LearningRateDropFactor, ...
                Regularisation, ...
                ValidationData ...
                );

save("TrainedEstimator.mat", "lstm")