classdef LSTM 
    properties 
       layers;
       options;
    end
    properties 
        CheckpointPath      = pwd + "/Simulation/CheckpointPath";
        CheckpointFrequency = 50;
        MaxEpochs;           
        MiniBatchSize;       
        InitialLearningRate;
        LearningRateDropPeriod;
        LearningRateDropFactor;
        Regularisation;
        ValidationData;
        ValidationFrequency = 10;
    end
    methods
        function Obj = Mute(Obj)
            
            Obj.options = trainingOptions(...
                    'adam', ...,
                    'CheckpointPath', Obj.CheckpointPath, ...
                    'CheckpointFrequency', Obj.CheckpointFrequency,...
                    'CheckpointFrequencyUnit', 'epoch', ...
                    'MaxEpochs', Obj.MaxEpochs, ...
                    'MiniBatchSize', Obj.MiniBatchSize, ...
                    'InitialLearnRate', Obj.InitialLearningRate, ...
                    'LearnRateSchedule', 'piecewise',...
                    'LearnRateDropPeriod', Obj.LearningRateDropPeriod,...
                    'LearnRateDropFactor', Obj.LearningRateDropFactor,...
                    'L2Regularization', Obj.Regularisation,...
                    'GradientThreshold', 1, ...
                    'Shuffle', 'never', ...
                    'Plots', 'none', ...
                    'ExecutionEnvironment', 'auto', ...
                    'Verbose', 1, ...
                    'ValidationData', Obj.ValidationData, ...
                    'ValidationFrequency', Obj.ValidationFrequency, ...
                    'VerboseFrequency', 10);
        end
        function Obj = UnMute(Obj)
            Obj.options = trainingOptions(...
                    'adam', ...,
                    'CheckpointPath', Obj.CheckpointPath, ...
                    'CheckpointFrequency', Obj.CheckpointFrequency,...
                    'CheckpointFrequencyUnit', 'epoch', ...
                    'MaxEpochs', Obj.MaxEpochs, ...
                    'MiniBatchSize', Obj.MiniBatchSize, ...
                    'InitialLearnRate', Obj.InitialLearningRate, ...
                    'LearnRateSchedule', 'piecewise',...
                    'LearnRateDropPeriod', Obj.LearningRateDropPeriod,...
                    'LearnRateDropFactor', Obj.LearningRateDropFactor,...
                    'L2Regularization', Obj.Regularisation,...
                    'GradientThreshold', 1, ...
                    'Shuffle', 'never', ...
                    'Plots', 'training-progress', ...
                    'ExecutionEnvironment', 'auto', ...
                    'Verbose', 1, ...
                    'ValidationData', Obj.ValidationData, ...
                    'ValidationFrequency', Obj.ValidationFrequency);
        end
        function Obj = GenerateLSTM(Obj, ...
                InputUnits, ...
                HiddenUnits, ...
                MiddleUnits, ...
                OutputUnits, ...
                MaxEpochs, ...
                MiniBatchSize, ...
                InitialLearningRate, ...
                LearningRateDropPeriod, ...
                LearningRateDropFactor, ...
                Regularisation, ...
                ValidationData)

            Obj.MiniBatchSize = MiniBatchSize;
            Obj.MaxEpochs = MaxEpochs;
            Obj.InitialLearningRate = InitialLearningRate;
            Obj.LearningRateDropPeriod = LearningRateDropPeriod;
            Obj.LearningRateDropFactor = LearningRateDropFactor;
            Obj.Regularisation = Regularisation;
            Obj.ValidationData = ValidationData;
            
            Obj.layers = [ ...
               sequenceInputLayer(InputUnits)
               layerNormalizationLayer

               
               bilstmLayer(HiddenUnits, 'OutputMode', 'sequence')
               fullyConnectedLayer(MiddleUnits)
               bilstmLayer(HiddenUnits, 'OutputMode', 'sequence')
              
               fullyConnectedLayer(OutputUnits)
               regressionLayer 
               ];
            Obj.options = trainingOptions(...
                    'adam', ...,
                    'CheckpointPath', Obj.CheckpointPath, ...
                    'CheckpointFrequency', Obj.CheckpointFrequency,...
                    'CheckpointFrequencyUnit', 'epoch', ...
                    'MaxEpochs', Obj.MaxEpochs, ...
                    'MiniBatchSize', Obj.MiniBatchSize, ...
                    'InitialLearnRate', Obj.InitialLearningRate, ...
                    'LearnRateSchedule', 'piecewise',...
                    'LearnRateDropPeriod', Obj.LearningRateDropPeriod,...
                    'LearnRateDropFactor', Obj.LearningRateDropFactor,...
                    'L2Regularization', Obj.Regularisation,...
                    'GradientThreshold', 1, ...
                    'Shuffle', 'never', ...
                    'Plots', 'training-progress', ...
                    'ExecutionEnvironment', 'auto', ...
                    'Verbose', 1, ...
                    'ValidationData', Obj.ValidationData, ...
                    'ValidationFrequency', Obj.ValidationFrequency);
        end
        function [Obj, net] = TrainLSTM(Obj, X, Y, retrain, net)
            if retrain == false 
                net = trainNetwork(X, Y, Obj.layers, Obj.options);
            else
                net = trainNetwork(X, Y, net.Layers, Obj.options);
            end
        end
        function [Obj, Y] = TestLSTM(Obj, net, X)
            Y = predict(net, X, 'MiniBatchSize', 1);
        end
    end
end